### ISSUE TITLE
CI Error : "redfish_emc_catalogs_test"

### ISSUE THREAD

**Issue by amymullins** [RackHD/RackHD#450]
Since 9/27, there has been a 2.2 % error frequency with the "redfish_emc_catalogs_test" (http://rackhdci.lss.emc.com/job/Continuous-Test/job/Continuous-Functional/10632/testReport/junit/(root)/redfish_emc_catalogs_test/redfish_emc_catalogs_test/)

Error Message
EMC Redfish Catalog size failure

Stacktrace
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/usr/lib/python2.7/unittest/case.py", line 1043, in runTest
    self._testFunc()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 296, in testng_method_mistake_capture_func
    compatability.capture_type_error(s_func)
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/compatability/exceptions_2_6.py", line 27, in capture_type_error
    func()
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/case.py", line 350, in func
    func(test_case.state.get_state())
  File "/home/jenkins/workspace/Continuous-Test/Continuous-Functional/build/test/tests/api/v1_1/redfish_endpoint_tests.py", line 229, in redfish_emc_catalogs_test
    assert_not_equal(len(catalog), 0, message='EMC Redfish Catalog size failure')
  File "/tmp/.venv/local/lib/python2.7/site-packages/proboscis/asserts.py", line 151, in assert_not_equal
    raise ASSERTION_ERROR(message)
AssertionError: EMC Redfish Catalog size failure

**Comment by jlongever** [comment]
This should resolve it https://github.com/RackHD/RackHD/pull/451

**Comment by amymullins** [comment]
Closing issue, specific "redfish_emc_catalogs_test" error no longer seen.

**Comment by changev** [comment]
@amymullins This error still can be found in Shanghai stack env, probability rate  decreases  from 100% to 60% or more.

see http://10.240.19.21/job/Release-Test/job/Release-Functional/
